services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --spider --no-verbose --tries=1 --timeout=5 http://localhost:9411/health || exit 1",
        ]
      start_interval: 2s
      interval: 10s
      timeout: 5s
      retries: 3

  weatherzip:
    container_name: ms-weatherzip
    build:
      context: .
      dockerfile: ./ms-weatherzip/Dockerfile
    restart: always
    ports:
      - "8001:8001"
    env_file:
      - ./ms-weatherzip/cmd/weatherzip/.env
    depends_on:
      zipkin:
        condition: service_healthy
  
  inputvalidate:
    container_name: ms-inputvalidate
    build:
      context: .
      dockerfile: ./ms-inputvalidate/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./ms-inputvalidate/cmd/inputvalidate/.env
    depends_on:
      zipkin:
       condition: service_healthy
