basePath: /
definitions:
  domain.WeatherResponse:
    properties:
      city:
        type: string
      temp_C:
        type: number
      temp_F:
        type: number
      temp_K:
        type: number
    type: object
  health.CPUStats:
    properties:
      cores:
        type: integer
      percent_used:
        items:
          type: number
        type: array
    type: object
  health.HealthStats:
    properties:
      cpu:
        $ref: '#/definitions/health.CPUStats'
      duration:
        type: string
      memory:
        $ref: '#/definitions/health.MemoryStats'
      message:
        type: string
      status:
        type: string
      time:
        type: string
      uptime:
        type: string
    type: object
  health.MemoryStats:
    properties:
      available:
        type: integer
      free:
        type: integer
      percent_used:
        type: number
      total:
        type: integer
      used:
        type: integer
    type: object
  web.CepRequest:
    properties:
      cep:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: me@vsouza.rio.br
    name: Vitor Rodrigues
    url: https://vsouza.rio.br/contact
  description: This is a simple API for validating input data (zip code), forwarding
    it to the weather service and returning the weather for a given location.
  license:
    name: MIT
    url: https://opensource.org/license/MIT
  title: Input Validation API
  version: "1.0"
paths:
  /:
    get:
      description: Exibe a saudação "Enjoy the silence!"
      produces:
      - text/plain
      responses:
        "200":
          description: Enjoy the silence!
          schema:
            type: string
        "500":
          description: Unable to write response
          schema:
            type: string
      summary: Exibe uma saudação
      tags:
      - Root
    post:
      consumes:
      - application/json
      description: Valida se o INPUT(CEP) contém 8 dígitos e encaminha para o serviço
        de clima se for válido.
      parameters:
      - description: CEP
        in: body
        name: cep
        required: true
        schema:
          $ref: '#/definitions/web.CepRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.WeatherResponse'
        "404":
          description: can not find zipcode
          schema:
            type: string
        "422":
          description: invalid zipcode
          schema:
            type: string
        "500":
          description: internal server error
          schema:
            type: string
      summary: Valida e encaminha um INPUT(CEP) para consulta de clima
      tags:
      - Input
  /health:
    get:
      description: Retorna informações sobre a saúde do serviço, como uso de CPU,
        memória e tempo de atividade
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/health.HealthStats'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Retorna informações sobre a saúde do serviço
      tags:
      - Health
swagger: "2.0"
